services:
  php:
    container_name: siler_issue554_php
    image: php:fpm
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: siler_issue554_nginx
    image: nginx
    links:
      - php
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 8000:80